### PR TITLE
return from function or shell if preparation of the app fails

### PR DESCRIPTION
**Pull request by zmiklank**
- use generic check function
 - update common
 - use return instead of exit for graceful termination

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
Most of the failures in the tests are related to the fastify client app. However all RHEL tests failed on some ansible stuff during preparation of the test environment. Need to look at it closer. It is probably not related to this PR.

**Comment by zmiklank** [comment]
Fixes: https://github.com/sclorg/s2i-nodejs-container/issues/379

**Comment by zmiklank** [comment]
[test]

**Review by phracek — APPROVED** [review]
Thanks for this pull request. I did not hit any issue.

**Pull request merged**
