### PR TITLE
Remove 10-ubi8 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by phracek** [comment]
LGTM. NodeJS 10 reached EOL cycle.

Let's test it.

[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
And what about NodeJS 10 for RHEL7. It reached EOL as well. Can you please remove it in this PR?

**Comment by yselkowitz** [comment]
Didn't you do that already in commit 22557bd8c8822d66c6142fc221f45b8a0073edfc?

**Comment by phracek** [comment]
I am very sorry, I have mixed RHEL8 and RHEL7. I totally forgot that I have already done it.
It looks like Friday in my mind. :)

**Pull request merged**
