### PR TITLE
add nodejs-16-minimal Dockerfile for rhel9

### PR DESCRIPTION
**Pull request by pkubatrh**
do not install weak dependencies in nodejs-16-minimal

### CODE REVIEW

**Comment by pkubatrh** [comment]
This PR waits on CI enablement for rhel9, but we can test the minimization changes in rhel8 at least

[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by phracek** [comment]
Let's test RHEL9 tests.

[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
RHEL9 fail should be fixed by https://github.com/sclorg/container-common-scripts/pull/266

**Comment by pkubatrh** [comment]
[test]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
