### PR TITLE
move test_latest_imagestreams case into openshift tests

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift][test-openshift-4]

**Comment by pkubatrh** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
`centos7 - openshift` failure is expected. Docker rate limit.

**Comment by phracek** [comment]
I have to analyze, why `rhel7-openshift` failed.

**Comment by pkubatrh** [comment]
Lets try once more
[test][test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
Tests are failing on OpenShift initialization. LGTM

**Review by phracek — APPROVED** [review]
I don't see any problem here. LGTM. Thanks.

**Pull request merged**
