### PR TITLE
Fix open files

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Review by zmiklank — CHANGES_REQUESTED** [review]
The commit dff6a25b654b6dadf106a508682a5f5d3bd91780 is named as "[Fix error caused by too many opened files](https://github.com/sclorg/s2i-nodejs-container/pull/421/commits/dff6a25b654b6dadf106a508682a5f5d3bd91780)", but in reality it bumps nodejs version in testing dockerfiles and changes strings in a test. Could you please rename it?

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
