### PR TITLE
chore: Add the pino logger to the testing suite

### PR DESCRIPTION
**Pull request by pacostas**
This PR adds pino logger back to the testing suite.

### CODE REVIEW

**Comment by lholmquist** [comment]
[test-all]

**Comment by pacostas** [comment]
No quite sure if the errors are related to the PR changes

**Comment by phracek** [comment]
@pacostas No, errors are caused by subsscription issues. They should be fixed now.

**Comment by phracek** [comment]
[test-all]

**Comment by pacostas** [comment]
Only one fails, the`RHEL9 - PyTest - Openshift 4 - 18-minimal`, and it does not have details in order to see the error. Probably is something else and not related to the PR.

**Comment by phracek** [comment]
It looks like an error in action. The logs are here: https://artifacts.osci.redhat.com/testing-farm/3a3b7919-928a-4b18-969c-439743811e2b/. Everything has passed.

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
