### PR TITLE
feat: adding the Opossum npm module to the test suite for NODE-1587

### PR DESCRIPTION
**Pull request by lholmquist**

### CODE REVIEW

**Comment by lholmquist** [comment]
[test]

**Comment by lholmquist** [comment]
@hhorak could you set off another test,  i think i figured out why there was failures

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by lholmquist** [comment]
[test]

**Comment by lholmquist** [comment]
[test-all]

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
On RHEL8 and Fedora (https://artifacts.dev.testing-farm.io/1fee0caa-ee97-4c1c-8f45-7267f974a42c/pipeline.log) it failed on reason:

RHEL8
```bash
 [PASSED] for 'clients' express
 [FAILED] for 'clients' pino
 [PASSED] for 'clients' prom-client
```
Fedora
```bash
10:08:42                 out:  [PASSED] for 'hw' test_build_express_webapp
10:08:42                 out:  [PASSED] for 'clients' express
10:08:42                 out:  [FAILED] for 'clients' pino
10:08:42                 out:  [PASSED] for 'clients' prom-client
```

**Comment by phracek** [comment]
[test-openshift]

**Comment by lholmquist** [comment]
[test]

**Comment by phracek** [comment]
OpenShift 4 failures are going to be fixed soon https://github.com/sclorg/container-common-scripts/pull/236.

**Comment by phracek** [comment]
@lholmquist Can you please rebase / update `common` submodule? It should be already part of it and OpenShift 4 tests should be working now. Thanks

**Comment by phracek** [comment]
As soon as it is rebased, I will re-schedule the tests.

**Comment by lholmquist** [comment]
[test]

**Comment by lholmquist** [comment]
@phracek rebased

**Comment by hhorak** [comment]
Tests seem to be stuck, re-running them.
[test]

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — APPROVED** [review]
Tests are passing. LGTM from my point of view.

**Pull request merged**
