### PR TITLE
Fix assemble cache clean order in 16-minimal, 18-minimal

### PR DESCRIPTION
**Pull request by SlouchyButton**
Removal of the cache has to be the last things done in the assemble script. Calling `npm` after deleting the cache folder will cause npm to recreate it - which will fail during the image test.

Other images apparently have it correctly, for some reason this error is present only in 16-minimal and 18-minimal.

### CODE REVIEW

**Comment by SlouchyButton** [comment]
[test]

**Review by lukaszachy — COMMENTED** [review]
LGTM (I'm afraid to click approve in the case it would unblock the merge bot)

**Comment by SlouchyButton** [comment]
> I'm afraid to click approve
afaik two approvals are needed and it's not yet merging automatically, only sending email that it would.

**Review by phracek — COMMENTED** [review]
LGTM, but is it enought to move cleaning operations before NPM_CACHE?

**Comment by phracek** [comment]
@lukaszachy @SlouchyButton Automatic merger is not enabled yet;). Do worry. See send only mails about PR and what is missing. Syncing upstream -> downstream for RHEL-9.5.0 is also disabled.

**Comment by phracek** [comment]
[test]

**Pull request merged**
