### PR TITLE
Add a python3 symlink to make the binary npm packages install-able

### PR DESCRIPTION
**Pull request by hhorak**
The link does not break the python3 installation.

```
$ podman run -ti --rm -u 0 ubi8/nodejs-14 bash
bash-4.4# python3
bash: python3: command not found
bash-4.4# ln -s /usr/libexec/platform-python /usr/bin/python3
bash-4.4# python3
Python 3.6.8 (default, Aug 18 2020, 08:33:21) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
bash-4.4# yum install python3
...
Complete!
bash-4.4# ls -la /usr/bin/python3
lrwxrwxrwx. 1 root root 25 Feb  8 14:21 /usr/bin/python3 -> /etc/alternatives/python3
bash-4.4# python3
Python 3.6.8 (default, Aug 18 2020, 08:33:21) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by pkubatrh** [comment]
lgtm, thanks!

**Pull request merged**
