### PR TITLE
do not wait for user input when enabling modules in 18-minimal

### PR DESCRIPTION
**Pull request by pkubatrh**
use modular content for 18-minimal in c9s

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-all]

**Comment by phracek** [comment]
@pkubatrh Please rebase it against master. OpenShift 4 tests should be passing now.

**Review by phracek — CHANGES_REQUESTED** [review]
The change itself LGTM. Please rebase the PR against master and schedule test again.
As soon as tests are triggered and green, except pino, we can merge it.

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
OpenShift 4 failures are filed here: https://github.com/sclorg/s2i-nodejs-container/issues/371

**Comment by phracek** [comment]
OpenShift 4 failures do not block this issue. Let's get merge it.

**Pull request merged**
