### PR TITLE
add buildpacks metadata to build images

### PR DESCRIPTION
**Pull request by pkubatrh**
Based on: https://github.com/buildpacks/spec/blob/main/platform.md#build-image

### CODE REVIEW

**Comment by pkubatrh** [comment]
Should not affect tests in any way, but lets run them to make sure

[test][test-openshift]

**Comment by mhdawson** [comment]
@pkubatrh can we also include in the minimal images as well ? Or is that covered somewhere else?

**Comment by pkubatrh** [comment]
>can we also include in the minimal images as well ? Or is that covered somewhere else?

We can, but it was my understanding that this change was for build images. Would the minimal image be more of a run image (or whatever it is called in buildstacks)?

**Comment by pkubatrh** [comment]
[test]

**Comment by mhdawson** [comment]
@pkubatrh the buildpacks use both a build and a run image, the metadata needs to be on both.

**Comment by pkubatrh** [comment]
@mhdawson Makes sense. Looking at the [metadata spec for run images](https://github.com/buildpacks/spec/blob/main/platform.md#run-image) it seems like the "must" metadata parts are slightly different - the `CNB_` environment variable definitions are missing.
I will add the definitions for the runtime minimal image to the other PR: https://github.com/sclorg/s2i-nodejs-container/pull/269

**Comment by mhdawson** [comment]
@pkubatrh I've not tested without the CNB_ env variables in the run image (since I only had one I used it for both).  

Will we easily be able to respin the images if it turns out we need them?

**Pull request merged**
