### PR TITLE
move to fedora 35

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
s2i-core should be now available.

[test]

**Comment by phracek** [comment]
See Fedora failure:

```bash

[91m[0mFedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
[91mErrors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[0m[91mError: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[0mThe command '/bin/sh -c yum -y module enable nodejs:$NODEJS_VERSION &&     MODULE_DEPS="make gcc gcc-c++ libatomic_ops" &&     INSTALL_PKGS="$MODULE_DEPS nodejs nodejs-nodemon npm nss_wrapper" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*'' returned a non-zero code: 1
make[1]: Leaving directory `/tmp/sclorg/s2i-nodejs-container'
make[1]: *** [12] Error 1
make: *** [build-serial] Error 2
```

**Comment by phracek** [comment]
By #326 PR I have changed the host for Fedora tests to C8S.

[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@pkubatrh Based on the results (https://artifacts.dev.testing-farm.io/09e955ed-8726-4732-a8c5-dd545f650d2f/work-c8smLiOWo/log.txt), tests are failing for this reason:
```bash
08:21:33                 out:  [PASSED] for 'app' test_nodemon_removed
08:21:33                 out:  [FAILED] for 'app' test_npm_cache_cleared
08:21:33                 out:  [PASSED] for 'app' test_npm_tmp_cleared
```

**Comment by phracek** [comment]
The error should be fixed by https://github.com/sclorg/s2i-nodejs-container/pull/321. Please rebase it. And all tests should be passing.

**Comment by pkubatrh** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. Fantastic work.

**Comment by phracek** [comment]
Only for sure.

[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
OpenShift 4 tests will be solved by https://github.com/sclorg/s2i-nodejs-container/issues/327

**Pull request merged**
