### PR TITLE
Deprecate version NodeJS 12 for RHEL-8

### PR DESCRIPTION
**Pull request by ljavorsk**
Image streams were removed in commit: de95fb8

### CODE REVIEW

**Comment by ljavorsk** [comment]
[test]

**Review by lholmquist — APPROVED** [review]

**Review by phracek — APPROVED** [review]
LGTM as well. But it should be merged add the end of April 2022, when NodeJS 12 will reach EOL!!!!!

**Comment by phracek** [comment]
@ljavorsk Can you please create a separate PR for removing NodeJS 12 imagestreams?

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Pull request merged**
