### PR TITLE
Add nodejs 6 version

### PR DESCRIPTION
**Pull request by luiscoms**

### CODE REVIEW

**Comment by bparees** [comment]
@luiscoms the nodejs images are normally based on the SCL packages, so this may require some discussion/feedback from the SCL team, but in the meantime you might be interested in:
https://github.com/openshift-s2i/s2i-nodejs-community

**Comment by luiscoms** [comment]
@bparees I open a PR there too https://github.com/openshift-s2i/s2i-nodejs-community/pull/3

**Comment by pkubatrh** [comment]
As nodejs version 6 has been added by https://github.com/sclorg/s2i-nodejs-container/commit/1b4473b0f16da25255f3b82b83e87a33c68d9e1b I think this can be closed.

Feel free to open another PR if you run into any issues with this version.

**Comment by luiscoms** [comment]
Thanks for ignore my MR lol

**Pull request closed without merging**
