### PR TITLE
Provide better description and summary

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
@kasicka What do you think?

**Comment by kasicka** [comment]
@hhorak Maybe change NodeJS to Node.js, so it's the same in the whole text.

**Comment by pkubatrh** [comment]
From what I can see the changes contained in this PR have already been pushed to master via https://github.com/sclorg/s2i-nodejs-container/commit/1b4473b0f16da25255f3b82b83e87a33c68d9e1b

@hhorak Is it ok to close this or am I missing something?

**Comment by omron93** [comment]
Closing. In case something is missing please reopen.

**Pull request closed without merging**
