### PR TITLE
Add test for latest_imagestreams

### PR DESCRIPTION
**Pull request by phracek**
The test checks if the latest version is present
in all image streams

https://github.com/sclorg/container-common-scripts/pull/153

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's run tests one more time.

[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test] [test-openshift]

**Comment by phracek** [comment]
Tests are passing, including the imagestream test. It should be enough. Merging.

**Pull request merged**
