### PR TITLE
Add symlink to test-lib-openshift.sh

### PR DESCRIPTION
**Pull request by pvalena**
[Changes Info](https://github.com/sclorg/s2i-python-container/pull/218#issuecomment-335276731)

### CODE REVIEW

**Comment by pvalena** [comment]
PTAL.

**Comment by pkubatrh** [comment]
Are these going to be modified for nodejs8 now that it is out?

**Comment by hhorak** [comment]
These templates should be part of the nodejs-ex example application.

**Comment by pvalena** [comment]
> These templates should be part of the nodejs-ex example application.

Correct. I'll move them to nodejs-ex repository instead. My bad.


> Are these going to be modified for nodejs8 now that it is out?

Anyway, this needs to be done in 3 steps:

- import already existing template (we're upstream now) 
- add simple tests for templates and ensure they pass
- update templates

**Comment by pkubatrh** [comment]
Is there any reason to keep this open?

**Comment by pvalena** [comment]
This can be actually merged now :)

**Comment by hhorak** [comment]
> Is there any reason to keep this open?

I don't think so, #172 delivers what was supposed to be delivered by this PR. Closing.

**Pull request closed without merging**
