### PR TITLE
Add support for internal Nexus registry

### PR DESCRIPTION
**Pull request by phracek**
Add NPM_MIRROR for reference to internal RedHat Nexus Registry.
We don't want to call registry.nodejs.org always during
testing each PR.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
Failures are expected because this PR (https://github.com/sclorg/container-common-scripts/pull/127) is not merged and we do not copy CA file into an image.

**Comment by phracek** [comment]
Reference https://github.com/sclorg/container-common-scripts/pull/127

**Comment by phracek** [comment]
Nexus registry is working properly for NodeJS container.

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by pkubatrh** [comment]
Seems like some networking issue, rerunning.
[test][test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by pkubatrh** [comment]
lgtm, thanks!

**Pull request merged**
