### PR TITLE
Update NodeJS Imagestreams with new version 20.

### PR DESCRIPTION
**Pull request by phracek**
Update NodeJS Imagestreams with new version 20 for RHEL9.

This pull request adds as NodeJS-20 as NodeJS-20-minimal images

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
RHEL7 OpenShift 3 test has failed because cluster did not start properly.

```bash
Checking if image registry.redhat.io/openshift3/ose-control-plane:v3.11 is available ...
Starting OpenShift using registry.redhat.io/openshift3/ose-control-plane:v3.11 ...
I1108 06:20:41.097528   18631 config.go:40] Running "create-master-config"
I1108 06:20:43.856522   18631 config.go:46] Running "create-node-config"
I1108 06:20:45.214179   18631 flags.go:30] Running "create-kubelet-flags"
I1108 06:20:45.677355   18631 run_kubelet.go:49] Running "start-kubelet"
I1108 06:20:45.876458   18631 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1108 06:21:28.889390   18631 interface.go:26] Installing "kube-proxy" ...
I1108 06:21:28.890128   18631 interface.go:26] Installing "kube-dns" ...
I1108 06:21:28.890142   18631 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1108 06:21:28.890177   18631 interface.go:26] Installing "openshift-apiserver" ...
I1108 06:21:28.890204   18631 apply_template.go:81] Installing "kube-proxy"
I1108 06:21:28.890214   18631 apply_template.go:81] Installing "openshift-apiserver"
I1108 06:21:28.891093   18631 apply_template.go:81] Installing "kube-dns"
I1108 06:21:28.891947   18631 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1108 06:21:34.725712   18631 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/nodejs-14-rhel7:1 failed.
errexit on line 63, common/test.sh
```

But this should not block this pull request.

**Review by zmiklank — CHANGES_REQUESTED** [review]
Seems like nodejs 14 is no longer supported for RHEL8. Would you consider adding a commit with its removal if that is the case, please?

Isn't it needed to add nodejs 20 templates also for RHEL8?

**Comment by phracek** [comment]
> Isn't it needed to add nodejs 20 templates also for RHEL8?

Sorry, I don't follow. Templates for version 20 are not disabled. It is done by function `test_nodejs_s2i_templates`. It is already covered by this row where version is entered https://github.com/sclorg/s2i-nodejs-container/blob/master/test/test-lib-nodejs.sh#L574

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
> > Isn't it needed to add nodejs 20 templates also for RHEL8?
> 
> Sorry, I don't follow. Templates for version 20 are not disabled. It is done by function `test_nodejs_s2i_templates`. It is already covered by this row where version is entered https://github.com/sclorg/s2i-nodejs-container/blob/master/test/test-lib-nodejs.sh#L574

I see you added imagestreams for nodejs20 for rhel9. Isn't it needed to cover rhel8 too?

**Comment by phracek** [comment]
[test-openshift]

> > > Isn't it needed to add nodejs 20 templates also for RHEL8?
> > 
> > 
> > Sorry, I don't follow. Templates for version 20 are not disabled. It is done by function `test_nodejs_s2i_templates`. It is already covered by this row where version is entered https://github.com/sclorg/s2i-nodejs-container/blob/master/test/test-lib-nodejs.sh#L574
> 
> I see you added imagestreams for nodejs20 for rhel9. Isn't it needed to cover rhel8 too?

Addressed by https://github.com/sclorg/s2i-nodejs-container/pull/414/commits/ba2604c90b11e1325718c84e4ec9174428f6fe9f

**Pull request merged**
