### PR TITLE
test: add testing of prom-client

### PR DESCRIPTION
**Pull request by mhdawson**
- add prom-client to the client packages to be tested
- tweak to handle packages with a dash in their name

Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by pkubatrh** [comment]
Needs to be rebasedsince e modified the tests a bit in #269 (test case definitions moved to a library file)

**Comment by hhorak** [comment]
@phracek should we care about the failing tests that do not run in Testing Farm or should we ignore those two?

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
> @phracek should we care about the failing tests that do not run in Testing Farm or should we ignore those two?

We talked about this off-line, the **centos7** a **fedora** tests are no longer active, once the rebase is done, it should vanish. That means we should be ok once **Testing Farm...** tests pass.

**Comment by mhdawson** [comment]
@hhorak rebased

**Comment by pkubatrh** [comment]
[test-all]

**Comment by phracek** [comment]
It looks like pino test is failing:

```bash
 [PASSED] for 'clients' express
 [FAILED] for 'clients' pino
 [PASSED] for 'clients' prom-client
```

Pino error log is here:
```bash
Step 8/9 : RUN /usr/libexec/s2i/assemble
 ---> Running in 330df9080275

[91m[0m---> Installing application source ...
---> Building your Node application from source
[91mnpm[0m[91m WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
[0m[91mnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[0m[91mnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0m[91mnpm WARN deprecated[0m[91m querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[0m[91mnpm WARN deprecated[0m[91m har-validator@5.1.5: this library is no longer supported
[0m[91mnpm WARN optional[0m[91m SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0m[91m
[0m[91mnpm ERR! code[0m[91m ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno[0m[91m ENOENT
[0m[91mnpm ERR! [0m[91menoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/isaacs/import-jsx.git
npm ERR! [0m[91menoent 
npm ERR! enoent 
npm ERR! enoent[0m[91m spawn git ENOENT
npm ERR! enoent[0m[91m This is related to npm not being able to find a file.
npm ERR! enoent 
[0m[91m
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2021-11-25T08_20_14_350Z-debug.log
[0mThe command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 1
S2I image 'f32/nodejs:12' test FAILED (exit code: 1)
Unable to find image 'f32/nodejs:12-pino' locally
Trying to pull repository docker.io/f32/nodejs ... 
/usr/bin/docker-current: repository docker.io/f32/nodejs not found: does not exist or no pull access.
See '/usr/bin/docker-current run --help'.
S2I image 'f32/nodejs:12' test FAILED (exit code: 125)
S2I image 'f32/nodejs:12' test FAILED (exit code: 125)
```

**Comment by phracek** [comment]
https://github.com/sclorg/container-common-scripts/pull/210 just for tracking.

**Comment by mhdawson** [comment]
Is there a link to more details on the failed run, from what's in the above I don't see anything related to running the pino tests. Possibly some sort of network issues trying to install?

**Comment by frenzymadness** [comment]
I'm far from being an expert here but might it be caused by the fact that 'f32/nodejs:12' does not contain git?

**Comment by phracek** [comment]
I guess, wrongly tagged image:

```bash
Unable to find image 'f32/nodejs:12-pino' locally
Trying to pull repository docker.io/f32/nodejs ... 
/usr/bin/docker-current: repository docker.io/f32/nodejs not found: does not exist or no pull access.
S
```

**Comment by frenzymadness** [comment]
> I guess, wrongly tagged image:
> 
> ```shell
> Unable to find image 'f32/nodejs:12-pino' locally
> Trying to pull repository docker.io/f32/nodejs ... 
> /usr/bin/docker-current: repository docker.io/f32/nodejs not found: does not exist or no pull access.
> S
> ```

If the image fails to build because there is an error in assemble script, it cannot exists locally :thinking:

**Comment by phracek** [comment]
@mhdawson I have opened an issue here: https://github.com/sclorg/s2i-nodejs-container/issues/302

But I don't have any idea, what is missing.

**Comment by phracek** [comment]
It looks like pino has fixed the issue by release 7.5.1.

[test-all]

**Comment by phracek** [comment]
https://github.com/pinojs/pino/issues/1252

**Comment by phracek** [comment]
Pino in version 7.5.1 fixed the problem with testing s2i-nodejs-container on Fedora.

**Comment by phracek** [comment]
The failed test for `RHEL8-OpenShift4` should be fixed by https://github.com/sclorg/s2i-nodejs-container/pull/304

**Comment by phracek** [comment]
@mhdawson Can you please also rebase this repository? Because of https://github.com/sclorg/s2i-nodejs-container/commit/e02af8ae0cbb0f2c8353704fd347c9324ef8334b.

Thank you.

**Comment by mhdawson** [comment]
@phracek rebased

**Comment by mhdawson** [comment]
Just heard from Matteo that there was a new version of Pino published to address the failures we were seeing :)

**Comment by phracek** [comment]
I know. The pino used by the latest tests was 7.5.1 and it was working properly including in our tests suite.

[test-all]

**Comment by phracek** [comment]
The test failed now on Fedora and RHEL8 here:

```bash
15:12:00                 out: [INFO] Running test test_run_binary_application .......
15:12:00                 out: 
15:12:00                 out: Initialized empty Git repository in /tmp/sclorg/s2i-nodejs-container/test/test-binary/.git/
[spin]
15:12:02                 out: Step 7/8 : RUN /usr/libexec/s2i/assemble
15:12:02                 out:  ---> Running in 7926ccabc721
15:12:02                 out: 
15:12:02                 out: ---> Installing application source ...
15:12:02                 out: ---> Installing all dependencies
15:12:05                 out: npm notice 
15:12:05                 out: npm notice New minor version of npm available! 8.0.0 -> 8.1.4
15:12:05                 out: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.4>
15:12:05                 out: npm notice Run `npm install -g npm@8.1.4` to update!
15:12:05                 out: npm notice 
15:12:05                 out: npm ERR! code 126
15:12:05                 out: npm ERR! path /opt/app-root/src/node_modules/node-rdkafka
15:12:05                 out: npm ERR! command failed
15:12:05                 out: npm ERR! command sh -c node-gyp rebuild
15:12:05                 out: npm ERR! sh: /usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin/node-gyp: Permission denied
15:12:05                 out: 
15:12:05                 out: npm ERR! A complete log of this run can be found in:
15:12:05                 out: npm ERR!     /opt/app-root/src/.npm/_logs/2021-12-01T15_12_05_365Z-debug.log
15:12:05                 out: The command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 126
15:12:05                 out: S2I image 'f33/nodejs:16' test FAILED (exit code: 1)
15:12:05                 out: /usr/bin/docker-current: Container ID file found, make sure the other container isn't running or delete /tmp/tmp.gxj9eToDmU.cid.
15:12:05                 out: See '/usr/bin/docker-current run --help'.
15:12:05                 out: Error response from daemon: Cannot kill container 60bb8ca9aa0e780b4a83f29536b7a84bb99443403061494862953aace576fd78: No such container: 60bb8ca9aa0e780b4a83f29536b7a84bb99443403061494862953aace576fd78
```

**Comment by mhdawson** [comment]
@phracek are the failures the same on both?  The Details links seem to be truncated and the one you provided the log for looks like a timeout.

**Comment by mhdawson** [comment]
Also the text you posted does not match in the one I looked at in log.txt ?

**Comment by mhdawson** [comment]
From the log.txt what I see is (looks to be ubi8./

```console
15:33:09                 out: not ok 35 - test/transport/syncfalse.test.js # time=306.961ms
15:33:09                 out:   ---
15:33:09                 out:   env: {}
15:33:09                 out:   file: test/transport/syncfalse.test.js
15:33:09                 out:   timeout: 480000
15:33:09                 out:   command: /usr/bin/node
15:33:09                 out:   args:
15:33:09                 out:     - test/transport/syncfalse.test.js
15:33:09                 out:   stdio:
15:33:09                 out:     - 0
15:33:09                 out:     - pipe
15:33:09                 out:     - 2
15:33:09                 out:   cwd: /opt/app-root/src
15:33:09                 out:   exitCode: null
15:33:09                 out:   signal: SIGTERM
15:33:09                 out:   ...
```

What I don't understand is `15:33:09                 out:   signal: SIGTERM` when it says `# time=306.961ms` and shows a timeout of `out:   timeout: 480000`

From the timestamps it also clearly did not run for a long time as they all end in the same 9sec?  Don't know if something outside of the tests could have sent the SIGTERM.

I also ran the test a few hundred times and don't see anything in the test being timing dependent. That along with the SIGTERM in less than 1 sec of test starting makes me think it was not an issue specific to the test itself.

**Comment by mhdawson** [comment]
Also ran 1000 times on ubi/nodejs-16 without failure.  Checked the Pino issues and no mention of this test either. So unless it recreates my guess is some external reason.

**Comment by mhdawson** [comment]
@phracek can you run again to see if it recreates on the QA machines?  If it's persistent there it will let us investigate.

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
From the Testing Farm - Fedora:
```bash
[1m[INFO] Running test test_run_binary_application .......[0m

[snipped]

[91m[0m---> Installing application source ...
---> Installing all dependencies
[91mnpm notice[0m[91m 
npm notice New minor version of npm available! 8.0.0 -> 8.2.0
[0m[91mnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.2.0>
npm notice Run `npm install -g npm@8.2.0` to update!
npm notice 
[0m[91mnpm ERR! code 126
npm ERR! path /opt/app-root/src/node_modules/node-rdkafka
[0m[91mnpm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
[0m[91mnpm ERR! sh: /usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin/node-gyp: Permission denied
[0m[91m
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2021-12-06T11_47_33_801Z-debug.log
[0mThe command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 126

[snipped]

 [PASSED] for 'clients' prom-client
 [FAILED] for 'binary' test_run_binary_application
```

From the Testing Farm - RHEL 8 point of view. It looks like we have a bug in the test suite. @phracek is going to investigate it.

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
I have tested RHEL 8 locally and all tests were passing.

[test]

**Comment by hhorak** [comment]
The fedora failure (`node-gyp: Permission denied`) should be fixed in F35: https://bugzilla.redhat.com/show_bug.cgi?id=2026615

**Comment by phracek** [comment]
@mhdawson Everything except Fedora is passing. Fedora is failing on NodeJS-12 version. Maybe this could be a problem.

**Review by phracek — APPROVED** [review]
LGTM. Tests are passing and we have a Bugzilla for it. https://bugzilla.redhat.com/show_bug.cgi?id=2026615

**Comment by phracek** [comment]
@hhorak I see your point, but we are still using Fedora 32. We have to fix it. I will create an issue for it.

**Comment by phracek** [comment]
https://github.com/sclorg/s2i-nodejs-container/issues/301

**Pull request merged**
