### PR TITLE
Use nss_wrapper-libs only with smaller footprint

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
It would be better to merge #400 before this, to not cause unnecessary conflicts in #400 (which is hard to rebase due to `mv/cp` combination).

**Comment by hhorak** [comment]
Tests fail on `fastify`, which is reported in #391

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
rebased, let's see whether it still works

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by phracek** [comment]
@hhorak I guess we need to build also `nodejs-20` for `nodejs-20-minimal`

See logs from RHEL8:
```bash
[master (root-commit) e5e36a5] Sample commit
 5 files changed, 130 insertions(+)
 create mode 100644 README.md
 create mode 100644 iisnode.yml
 create mode 100644 package.json
 create mode 100644 server.js
 create mode 100644 web.config
Testing the production image build
Image ubi8/nodejs-20 not found, trying to pull ubi8/nodejs-20 from registry
Resolving "ubi8/nodejs-20" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull registry.access.redhat.com/ubi8/nodejs-20:latest...
Trying to pull registry.redhat.io/ubi8/nodejs-20:latest...
Trying to pull docker.io/ubi8/nodejs-20:latest...
```

**Review by phracek — APPROVED** [review]
LGTM.

**Comment by phracek** [comment]
rebased

[test]

**Pull request merged**
