### PR TITLE
fix incorrect use of HOME in Dockerfile for minimal images

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-all]

**Comment by pkubatrh** [comment]
Seems like Centos7 CI is failing because origin-clients-3.11.0-1.el7.git.0.62803d0.x86_64 rpm package is not available.

**Comment by pkubatrh** [comment]
Let's try once more [test]

**Comment by phracek** [comment]
Logs for RHEL-7 are here: http://artifacts.osci.redhat.com/testing-farm/0b0fd85e-432c-4d96-8b54-16d767c3b160/

**Review by phracek — APPROVED** [review]
Everything LGTM. Thanks for the PR! But I don't follow why moving PATH to later on ENV instead of this once.

**Comment by pkubatrh** [comment]
Tests passing for me locally for the node 14 image. Let's try one more time [test]

**Comment by phracek** [comment]
Fedora tests are fixed by #323

**Pull request merged**
