### PR TITLE
Do not use parent dir

### PR DESCRIPTION
**Pull request by phracek**
Examples are symlinked into test directory

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@pkubatrh WDYT?

**Comment by pkubatrh** [comment]
LGTM, though would have been better if this was part of #264 but that one is already merged.

**Comment by phracek** [comment]
Next time it will be better;)

**Pull request merged**
