### PR TITLE
Support testing NodeJS container in OpenShift 4 environment

### PR DESCRIPTION
**Pull request by phracek**
This commit brings a new functionality for testing SCL images under OpenShift 4.4 environment

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
https://github.com/sclorg/container-common-scripts/pull/150

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by pkubatrh** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
OpenShift 4 tests failure should be fixed by https://github.com/sclorg/rhscl-container-ci/pull/41

**Comment by phracek** [comment]
JJB is updated

[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
OpenShift 4 testing error is fixed by https://github.com/sclorg/container-common-scripts/pull/171

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
OpenShift 4 failed because of s2i-nodejs 14 version is not built. This bug is fixed by https://github.com/sclorg/container-common-scripts/pull/172

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
Test failed on pod/command-app. Let's try one more time. And analyze failure.

[test-openshift-4]

**Comment by phracek** [comment]
Some CI issues with expiration. Let's try one more time

[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by pkubatrh** [comment]
Updated F33 s2i-base image is out now, lets try again for green tests.
[test]

**Comment by phracek** [comment]
Alleluja :)

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Testing new Jenkins

[test]

**Comment by phracek** [comment]
Testing new Jenkins

[test]

**Comment by phracek** [comment]
Testing new Jenkins

[test]

**Comment by phracek** [comment]
Testing new Jenkins

[test]

**Comment by phracek** [comment]
Testing new Jenkins

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
New Jenkins Job for RHEL7

[test]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 3 and 4

[test][test-openshift][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 3 and 4

[test][test-openshift][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift  4

[test][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 4

[test][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 4

[test][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 4

[test][test-openshift-4]

**Comment by phracek** [comment]
Another test in new Jenkins instance also for OpenShift 4

[test-openshift-4]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
This PR is blocked by https://github.com/sclorg/container-common-scripts/pull/192

**Comment by phracek** [comment]
The test in OpenShift 4 will be solved automatically as soon as #272 is merged.

**Comment by phracek** [comment]
@yselkowitz I have removed in this pull request NodeJS 10 from the imagestreams. NodeJS reached EOL. Does it make sense to you?

**Comment by yselkowitz** [comment]
> @yselkowitz I have removed in this pull request NodeJS 10 from the imagestreams. NodeJS reached EOL. Does it make sense to you?

Sorry, I don't understand.  How does this relate to #271?

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
CI died

[test][test-openshift-4]

**Comment by phracek** [comment]
OpeShift 4 CI is gack again.

Let's try run test suite

[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
OpenShift 4 tests are failing on this error only for version 14. The rest is fine.
```bash
In project sclorg-test-25857 on server <IP>

<IP>(svc/nodejs-testing)
  dc/nodejs-testing deploys istag/nodejs-testing:latest <-
    bc/nodejs-testing source builds https://github.com/sclorg/nodejs-ex.git#master on istag/nodejs:14
      not built yet
    deployment #1 waiting on image or update

Warnings:
  * bc/nodejs-testing builds from istag/nodejs:14, but the image stream tag does not exist.
    try: istag/nodejs:14 needs to be imported.
  * The image trigger for dc/nodejs-testing will have no effect until istag/nodejs-testing:latest is imported or created by a build.
  * istag/nodejs-testing:latest needs to be imported or created by a build.
    try: oc start-build nodejs-testing

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
```

**Comment by phracek** [comment]
rebased 

[test][test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
@hhorak @pkubatrh Finally. All check PASSED :) Can we merge it?

**Pull request merged**
