### PR TITLE
Support quay.io registry

### PR DESCRIPTION
**Pull request by phracek**
This commit adds support for Quay.io registry instead of Docker.IO

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
@phracek Please rebase for https://github.com/sclorg/s2i-nodejs-container/pull/257, that should make the rhel7 tests pass

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
CentOS7 test failed on testing the latest imagestream version.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by fila43** [comment]
LGTM

**Comment by phracek** [comment]
[test][test-openshift]

**Pull request merged**
