### PR TITLE
Remove version 10. Reached EOL

### PR DESCRIPTION
**Pull request by phracek**
This pull request deprecated Node JS 10 which reaches EOL support.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
`Jenkins-CI` can be ignored as for docker as for openshift tests. We have only `SCLorg-CI` now.

**Comment by phracek** [comment]
OpenShift 3 does not startup properly. The rest is fine.
Let's try it again.

[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by pkubatrh** [comment]
LGTM, can be merged once tests pass

**Comment by phracek** [comment]
OpenShift tests failed here:

`centos7 - openshift` - OpenShift does not start
`SCLorg-CI for rhel7 - openshift` failed at the end. Problem with deleting project and OpenShift services.

https://github.com/sclorg/container-common-scripts/issues/195

**Pull request merged**
